baseURL: https://blog.zero-iee.com
languageCode: de-de
title: ZERO GmbH Tech Blog
theme: anubis-zero

defaultContentLanguage: de

languages:
  de: 
    languageName: Deutsch
    weight: 1
  en:
    languageName: English
    weight: 2

params:
  style: auto-without-switcher
  readMore: true
  social:
  - id: github
    name: zero-iee
  - id: linkedin
    url: https://de.linkedin.com/company/zero-iee
